apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vy11dwf53-go
  janus-idp.io/tekton: vy11dwf53-go
  backstage.io/kubernetes-id: vy11dwf53-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vy11dwf53-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
